### ISSUE TITLE
Waterfall 1.20 – yamler error

### ISSUE THREAD

**Issue by VladOliinyk** [Cube-Space/Yamler#33]
It seems like 1.20 has finally broken the support of Yamler and [Bungeecord RCON](https://www.spigotmc.org/resources/bungeecord-rcon.5817/). 

```
[14:23:39 WARN]: Exception encountered when loading plugin: BungeeRcon
java.lang.NoSuchMethodError: org.yaml.snakeyaml.representer.Representer: method 'void <init>()' not found
        at net.cubespace.Yamler.Config.BaseConfigMapper.<init>(BaseConfigMapper.java:27) ~[?:?]
        at net.cubespace.Yamler.Config.ConfigMapper.<init>(ConfigMapper.java:13) ~[?:?]
        at net.cubespace.Yamler.Config.YamlConfig.<init>(YamlConfig.java:12) ~[?:?]
        at net.cubespace.Yamler.Config.Config.<init>(Config.java:4) ~[?:?]
        at net.borlcand.rcon.config.MainConfig.<init>(MainConfig.java:10) ~[?:?]
        at net.borlcand.rcon.config.ConfigManager.<clinit>(ConfigManager.java:7) ~[?:?]
        at net.borlcand.rcon.Rcon.startListener(Rcon.java:38) ~[?:?]
        at net.borlcand.rcon.Rcon.onEnable(Rcon.java:34) ~[?:?]
        at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:316) ~[waterfall-1.20-536.jar:git:Waterfall-Bootstrap:1.20-R0.1-SNAPSHOT:ec41547:536]
        at net.md_5.bungee.BungeeCord.start(BungeeCord.java:299) ~[waterfall-1.20-536.jar:git:Waterfall-Bootstrap:1.20-R0.1-SNAPSHOT:ec41547:536]
        at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:67) ~[waterfall-1.20-536.jar:git:Waterfall-Bootstrap:1.20-R0.1-SNAPSHOT:ec41547:536]
        at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15) ~[waterfall-1.20-536.jar:git:Waterfall-Bootstrap:1.20-R0.1-SNAPSHOT:ec41547:536]
```

**Comment by yannicklamprecht** [comment]
Bungee updated Yaml library and the constructor changed.
https://github.com/yannicklamprecht/Yamler/actions/runs/5696210275
